# Generated by Django 5.1.7 on 2025-03-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True)),
                ('imagem', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True, null=True)),
                ('texto_botao', models.CharField(blank=True, max_length=30, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('assunto', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False)),
                ('respondido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='PaginaConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('sobre', 'Sobre Nós'), ('estrutura', 'Nossa Estrutura'), ('contato', 'Contato'), ('localizacao', 'Localização'), ('politica', 'Política de Privacidade'), ('termos', 'Termos de Uso'), ('faq', 'Perguntas Frequentes'), ('regras', 'Regras da Pousada'), ('outros', 'Outros')], max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('conteudo', models.TextField()),
                ('imagem_destaque', models.ImageField(blank=True, null=True, upload_to='paginas/')),
                ('meta_descricao', models.CharField(blank=True, help_text='Descrição para SEO', max_length=160, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem_menu', models.IntegerField(default=0)),
                ('mostrar_no_menu', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página de Conteúdo',
                'verbose_name_plural': 'Páginas de Conteúdo',
                'ordering': ['ordem_menu'],
            },
        ),
    ]
