# Generated by Django 5.1.7 on 2025-03-24 22:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O telefone deve estar no formato (XX) XXXXX-XXXX ou (XX) XXXX-XXXX', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')])),
                ('data_nascimento', models.DateField()),
                ('estado_civil', models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável'), ('outros', 'Outros')], default='solteiro', max_length=15)),
                ('tipo_documento', models.CharField(choices=[('cpf', 'CPF'), ('rg', 'RG'), ('passaporte', 'Passaporte'), ('cnh', 'CNH')], max_length=10)),
                ('documento', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=150)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('vip', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ultima_hospedagem', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hóspede',
                'verbose_name_plural': 'Hóspedes',
                'ordering': ['nome'],
                'unique_together': {('tipo_documento', 'documento')},
            },
        ),
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='hospedes.hospede')),
            ],
            options={
                'verbose_name': 'Preferência',
                'verbose_name_plural': 'Preferências',
                'ordering': ['hospede', 'categoria'],
            },
        ),
    ]
