# Generated by Django 5.1.7 on 2025-03-24 22:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('manutencao', 'Manutenção'), ('limpeza', 'Limpeza'), ('alimentacao', 'Alimentação'), ('energia', 'Energia Elétrica'), ('agua', 'Água'), ('internet', 'Internet'), ('funcionarios', 'Funcionários'), ('impostos', 'Impostos'), ('marketing', 'Marketing'), ('outros', 'Outros')], max_length=20)),
                ('status', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=15)),
                ('data_despesa', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='despesas/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data_despesa'],
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('aluguel', 'Aluguel de Ponto Comercial'), ('freela', 'Serviços Freelancer'), ('eventos', 'Eventos'), ('produtos', 'Venda de Produtos'), ('outros', 'Outros')], max_length=20)),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('pendente', 'Pendente'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=15)),
                ('data_receita', models.DateField()),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='receitas/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('recorrente', models.BooleanField(default=False, help_text='Se é uma receita recorrente (mensal)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['-data_receita'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('transferencia', 'Transferência Bancária'), ('deposito', 'Depósito Bancário'), ('outros', 'Outros')], max_length=20)),
                ('status', models.CharField(choices=[('aprovado', 'Aprovado'), ('pendente', 'Pendente'), ('recusado', 'Recusado'), ('estornado', 'Estornado')], default='pendente', max_length=15)),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('codigo_transacao', models.CharField(blank=True, max_length=50, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('reserva_pendente', 'Reserva com Pagamento Pendente'), ('despesa_vencendo', 'Despesa Próxima do Vencimento'), ('receita_atrasada', 'Receita em Atraso'), ('ocupacao_baixa', 'Baixa Ocupação'), ('manutencao', 'Manutenção Necessária'), ('estoque', 'Estoque Baixo'), ('outros', 'Outros')], max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('visualizado', models.BooleanField(default=False)),
                ('resolvido', models.BooleanField(default=False)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='reservas.reserva')),
                ('despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='financeiro.despesa')),
                ('receita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='financeiro.receita')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-prioridade', '-data_criacao'],
            },
        ),
    ]
