# Generated by Django 5.1.7 on 2025-03-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('hospedagem', 'Hospedagem'), ('aluguel', 'Aluguel de Ponto Comercial'), ('freela', 'Serviços Freelancer'), ('eventos', 'Eventos'), ('produtos', 'Venda de Produtos'), ('outros', 'Outros')], max_length=20),
        ),
    ]
