# Generated by Django 5.1.7 on 2025-03-25 21:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='desconto_porcentagem',
            field=models.IntegerField(default=0, help_text='Desconto em % (0-50%) que pode ser aplicado pelo proprietário', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='quarto',
            name='proxima_manutencao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarto',
            name='ultima_limpeza',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LimpezaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('limpeza', 'Limpeza'), ('manutencao', 'Manutenção'), ('vistoria', 'Vistoria'), ('reparo', 'Reparo')], max_length=15)),
                ('descricao', models.TextField()),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=15)),
                ('data_agendamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('tempo_estimado', models.PositiveIntegerField(default=30, help_text='Tempo estimado em minutos')),
                ('responsavel', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('custo', models.DecimalField(decimal_places=2, default=0, help_text='Custo em R$', max_digits=10)),
                ('checklist_completo', models.BooleanField(default=False)),
                ('aprovado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='quartos.quarto')),
            ],
            options={
                'verbose_name': 'Tarefa de Limpeza/Manutenção',
                'verbose_name_plural': 'Tarefas de Limpeza/Manutenção',
                'ordering': ['-data_agendamento', 'status'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistLimpeza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('concluido', models.BooleanField(default=False)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_checklist', to='quartos.limpezamanutencao')),
            ],
            options={
                'verbose_name': 'Item do Checklist',
                'verbose_name_plural': 'Itens do Checklist',
                'ordering': ['id'],
            },
        ),
    ]
