# Generated by Django 5.1.7 on 2025-04-05 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospedes', '0001_initial'),
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_checkin', models.DateField()),
                ('data_checkout', models.DateField()),
                ('numero_pessoas', models.PositiveIntegerField()),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('pago_50', models.BooleanField(default=False)),
                ('confirmado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospedes.hospede')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quartos.quarto')),
            ],
        ),
    ]
