# Generated by Django 5.1.7 on 2025-03-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='status_anterior',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('em_andamento', 'Em Andamento'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída'), ('no_show', 'No-Show')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historico',
            name='status_novo',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('em_andamento', 'Em Andamento'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída'), ('no_show', 'No-Show')], max_length=15),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('em_andamento', 'Em Andamento'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída'), ('no_show', 'No-Show')], default='pendente', max_length=20),
        ),
    ]
