# Generated by Django 5.1.7 on 2025-03-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_historico_status_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='desconto_diaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto por diária'),
        ),
    ]
